### PR TITLE
Fix build failure if java_library has no META-INF/MANIFEST.MF

### LINKED ISSUE #130: Build failures for targets matching `*spring-boot-*` or `*spring_boot_*`
Since https://github.com/salesforce/rules_spring/commit/67c64580de5a52977e668455e4c689ae911ff9c0, spring boot rules with names matching `*spring-boot-*` or `*spring_boot_*` can with an error such as the following if their corresponding `java_library` does not contain a `META-INF/MANIFEST.MF` file:

```
java.nio.file.NoSuchFileException:
bazel-out/k8-fastbuild/bin/foobar/tests/testdata/spring_boot_example/MANIFEST.MF
    at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92) 
    at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
    at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
    at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
    at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:149)
    at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
    at java.base/java.nio.file.Files.readAttributes(Files.java:1763)
    at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1225)
    at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:727)
    at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:844)
    at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:247)
    at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:177)
    at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:148)
    at jdk.jartool/sun.tools.jar.Main.extract(Main.java:1389)
    at jdk.jartool/sun.tools.jar.Main.run(Main.java:403)
    at jdk.jartool/sun.tools.jar.Main.main(Main.java:1681)
```

The root cause is that the `.jar` corresponding to the `java_library` target matches the check in https://github.com/salesforce/rules_spring/blob/67c64580de5a52977e668455e4c689ae911ff9c0/springboot/write_manifest.sh#L15, which causes the next command to attempt to unpack `META-INF/MANIFEST.MF` from the `.jar`. Since this `.jar` is build with `java_library`, it usually does not contain `META-INF/MANIFEST.MF`, which causes the script to error out.

A fix could be to catch the failure in the `jar` command and continue with the next match in the loop.

### PR DESCRIPTION
**Pull request by fmeum**
Fixes #130.

### CODE REVIEW

**Comment by fmeum** [comment]
Signing the CLA failed with an error and I can't repeat the signing flow as its shown as completed. I contacted contactoss-cla@salesforce.com about this.

**Comment by fmeum** [comment]
My email to contactoss-cla@salesforce.com bounced back saying that this account does not exist. What do I need to do to sign the CLA now?

**Comment by plaird** [comment]
@fmeum  Sorry for the trouble, I am reaching out internally to see how to proceed with the CLA issue.

**Comment by anish** [comment]
@fmeum could you try [the signing link](https://cla.salesforce.com/sign-cla?prUrl=https%3A%2F%2Fgithub.com%2Fsalesforce%2Frules_spring%2Fpull%2F131) again ?

**Comment by fmeum** [comment]
@anish It still says "You already signed the CLA on 2021-06-08" after logging in with GitHub and doesn't let me proceed.

**Comment by anish** [comment]
I fixed it manually for now @fmeum , we will investigate the issue on the backend

**Comment by plaird** [comment]
Thanks @fmeum for the fix.
Thanks @anish for the CLA solution.

**Pull request merged**
