### PR TITLE
Updates readme

### PR DESCRIPTION
**Pull request by Marcus-Rosti**
Reflects new release

### CODE REVIEW

**Comment by Marcus-Rosti** [comment]
@plaird sorry, I signed the cla but it didn't retrigger, sorry about that, not sure how to rerun it

**Comment by plaird** [comment]
OK let me close it and reopen it....

**Comment by plaird** [comment]
Thanks for the contribution @Marcus-Rosti, I forgot to update the README. Sorry the CLA was a pain, closing and reopening was the trick.

**Pull request merged**
